apiVersion: v1
kind: Service
metadata:
  name: phpadm-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.241
  selector:
    app: phpadm
  ports:
    - name: phpadm
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpadm-deployment
spec:
  selector:
    matchLabels:
      app: phpadm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpadm
    spec:
      containers:
        - name: phpadm
          image: phpadm_img
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
