apiVersion: v1
kind: Service
metadata:
  name: sql-svc
spec:
  selector:
    app: sql
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql
  labels:
    app: sql
spec:
  selector:
    matchLabels:
      app: sql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
        - image: sql_img
          name: sql-container
          imagePullPolicy: Never
          ports:
            - containerPort: 3306
              name: sql-port