apiVersion: v1
kind: Service
metadata:
  name: word-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.241
  selector:
    app: word
  ports:
    - name: word
      protocol: TCP
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-deployment
spec:
  selector:
    matchLabels:
      app: word
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: word
    spec:
      containers:
        - name: word
          image: word_img
          imagePullPolicy: Never
          ports:
            - containerPort: 5050